{
 "title": "Open Telemetry Monitor Prom Live",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Projects",
    "query": {
     "query": "label_values(project_name{projectkey!=\"unknown\"},projectkey)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<header style=\"display:flex;align-items:center;background:#094780;padding:10px;\"><img src=\"https://www.magicsoftware.com/wp-content/uploads/2018/05/magic-logo-blue@3x.png\" alt=\"Dashboard Logo\" style=\"width:55px;height:50px;margin-right:10px;\"><h1 style=\"color:white;font-size:18px;margin:0;font-weight:bold;\">Open Telemetry Monitoring Dashboard</h1></header>\n"
   }
  },
  {
   "title": "Total Projects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (projectkey) (project_name{job=\"summary_metrics\", projectkey=~\"$Projects\"} == 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_errors_current_session{job=\"summary_metrics\", projectkey=~\"$Projects\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors in Last 1 hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "errors_last_hour{job=\"summary_metrics\", projectkey=~\"$Projects\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Flows Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_flows_current_session{job=\"summary_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flows in Last 1 hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flows_last_hour{job=\"summary_metrics\", projectkey=~\"$Projects\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  project_status{job=\"summary_metrics\", projectkey=~\"$Projects\"} != 0\r\n)\r\n",
     "legendFormat": "{{projectkey}}"
    }
   ]
  }
 ]
}