{
 "title": "Server Detail",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Projects",
    "query": {
     "query": "label_values(project_name{projectkey!=\"unknown\"},projectkey)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<header style=\"display:flex;align-items:center;background:#094780;padding:10px;\"><img src=\"https://www.magicsoftware.com/wp-content/uploads/2018/05/magic-logo-blue@3x.png\" alt=\"Dashboard Logo\" style=\"width:55px;height:50px;margin-right:10px;\"><h1 style=\"color:white;font-size:18px;margin:0;font-weight:bold;\">Open Telemetry Monitoring Dashboard</h1></header>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 3 },
   "options": {
    "content": "<a href=\"/d/aegeg6qwve51cf/open-telemetry-monitor-prom-live?orgId=1&from=now-1h&to=now&timezone=browser&var-Projects=$__all&refresh=1m\" style=\"text-decoration:none;color:#000000;font-size:50px;padding:0;\">←</a>"
   }
  },
  {
   "title": "Server Status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "server_status{job=\"summary_metrics\", projectkey=~\"$Projects\"} != 0",
     "legendFormat": "{{projectkey}}: {{serverid}}"
    }
   ]
  },
  {
   "title": "Session Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_session_start{job=\"summary_metrics\", projectkey=~\"$Projects\"} / 1000000",
     "legendFormat": "{{projectkey}}_{{serverid}}"
    }
   ]
  },
  {
   "title": "Latest Transaction Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_transaction_time{job=\"summary_metrics\", projectkey=~\"$Projects\"} / 1000000",
     "legendFormat": "{{projectkey}}_{{serverid}}"
    }
   ]
  },
  {
   "title": "Server Uptime in Hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime_current_session_sec{job=\"summary_metrics\", projectkey=~\"$Projects\"} / 60 / 60 ",
     "legendFormat": "{{projectkey}}_{{serverid}}"
    }
   ]
  },
  {
   "title": "Server Details",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "project_name{projectkey!=\"unknown\", job=\"summary_metrics\", projectkey=~\"$Projects\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_status{projectkey!=\"unknown\", serverid!=\"unknown\", job=\"summary_metrics\", projectkey=~\"$Projects\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_errors_current_session{projectkey!=\"unknown\", serverid!=\"unknown\", job=\"summary_metrics\", projectkey=~\"$Projects\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "errors_last_hour{projectkey!=\"unknown\", serverid!=\"unknown\", job=\"summary_metrics\", projectkey=~\"$Projects\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_flows_current_session{projectkey!=\"unknown\", serverid!=\"unknown\", job=\"summary_metrics\", projectkey=~\"$Projects\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "flows_last_hour{projectkey!=\"unknown\", serverid!=\"unknown\", job=\"summary_metrics\", projectkey=~\"$Projects\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\r\n  project_name{projectkey!=\"unknown\", job=\"summary_metrics\", projectkey=~\"$Projects\", serverid=~\".+\"}, \r\n  \"project_server\", \r\n  \":\", \r\n  \"projectkey\", \r\n  \"serverid\"\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}